// ExecutivePDFReport.tsx — تقرير تنفيذي PDF
// Generates a professional PDF report with key metrics, bottlenecks, and project status
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileDown, Loader2, FileText, AlertTriangle, CheckCircle2, BarChart3 } from 'lucide-react';
import { useData } from '../../contexts/DataContext';

const ExecutivePDFReport: React.FC = () => {
  const { projects, technicalRequests, clearanceRequests, projectWorks, currentUser } = useData();
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);

    try {
      // Dynamic imports to keep bundle small
      const { default: jsPDF } = await import('jspdf');

      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const now = Date.now();

      // Add Cairo font (fallback to Helvetica for PDF — Arabic rendering limited in jsPDF)
      doc.setFont('Helvetica');

      // ── Header ──
      doc.setFillColor(27, 43, 72); // navy
      doc.rect(0, 0, pageW, 40, 'F');
      doc.setFillColor(233, 93, 34); // orange accent line
      doc.rect(0, 40, pageW, 2, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.text('Dar Wa Emaar - Executive Report', pageW / 2, 18, { align: 'center' });
      doc.setFontSize(10);
      doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), pageW / 2, 28, { align: 'center' });
      doc.text(`Generated by: ${currentUser?.name || 'System'}`, pageW / 2, 34, { align: 'center' });

      let y = 52;

      // ── KPIs Section ──
      doc.setTextColor(27, 43, 72);
      doc.setFontSize(14);
      doc.text('Key Performance Indicators', 15, y);
      y += 10;

      const totalProjects = projects.length;
      const completedProjects = projects.filter(p => p.status === 'completed' || p.progress >= 100).length;
      const activeProjects = totalProjects - completedProjects;
      const avgProgress = totalProjects > 0 ? Math.round(projects.reduce((s, p) => s + (p.progress || 0), 0) / totalProjects) : 0;
      const totalWorks = projectWorks.length;
      const completedWorks = projectWorks.filter(w => w.status === 'completed').length;
      const bottlenecks = projectWorks.filter(w => {
        if (w.status === 'completed') return false;
        const created = new Date(w.created_at).getTime();
        return (now - created) > 7 * 24 * 3600000;
      }).length;

      const kpis = [
        ['Total Projects', String(totalProjects)],
        ['Completed', String(completedProjects)],
        ['Active', String(activeProjects)],
        ['Avg. Progress', `${avgProgress}%`],
        ['Total Tasks', String(totalWorks)],
        ['Completed Tasks', String(completedWorks)],
        ['Bottlenecks', String(bottlenecks)],
        ['Technical Requests', String(technicalRequests.length)],
        ['Deed Records', String(clearanceRequests.length)],
      ];

      // KPI grid
      const colW = (pageW - 30) / 3;
      kpis.forEach(([label, value], i) => {
        const col = i % 3;
        const row = Math.floor(i / 3);
        const x = 15 + col * colW;
        const cellY = y + row * 18;
        
        doc.setFillColor(245, 247, 250);
        doc.roundedRect(x, cellY, colW - 4, 15, 3, 3, 'F');
        
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text(label, x + 4, cellY + 5.5);
        
        doc.setFontSize(14);
        doc.setTextColor(27, 43, 72);
        doc.text(value, x + 4, cellY + 12.5);
      });

      y += Math.ceil(kpis.length / 3) * 18 + 10;

      // ── Project Status Table ──
      doc.setFontSize(14);
      doc.setTextColor(27, 43, 72);
      doc.text('Project Status Overview', 15, y);
      y += 8;

      // Table header
      doc.setFillColor(27, 43, 72);
      doc.rect(15, y, pageW - 30, 8, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text('Project', 18, y + 5.5);
      doc.text('Progress', 92, y + 5.5);
      doc.text('Status', 135, y + 5.5);
      doc.text('Tasks', 172, y + 5.5);
      y += 8;

      // Table rows (top 20)
      projects.slice(0, 20).forEach((p, i) => {
        const works = projectWorks.filter(w => w.projectId === p.id);
        const completed = works.filter(w => w.status === 'completed').length;
        
        if (i % 2 === 0) {
          doc.setFillColor(248, 250, 252);
          doc.rect(15, y, pageW - 30, 7, 'F');
        }

        doc.setFontSize(7);
        doc.setTextColor(50, 50, 50);
        doc.text((p.title || p.name || '').substring(0, 38), 18, y + 4.5);
        
        // Progress bar
        const barX = 92;
        const barW = 25;
        doc.setFillColor(230, 230, 230);
        doc.roundedRect(barX, y + 1.5, barW, 3, 1.5, 1.5, 'F');
        const progress = p.progress || 0;
        if (progress > 0) {
          const fillColor = progress >= 100 ? [34, 197, 94] : progress >= 50 ? [233, 93, 34] : [239, 68, 68];
          doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
          doc.roundedRect(barX, y + 1.5, barW * (progress / 100), 3, 1.5, 1.5, 'F');
        }
        doc.text(`${progress}%`, barX + barW + 2, y + 4.5);

        doc.text(p.status || 'active', 135, y + 4.5);
        doc.text(`${completed}/${works.length}`, 172, y + 4.5);
        
        y += 7;
        
        // Page break
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      });

      y += 8;

      // ── Bottleneck Alert Section ──
      if (bottlenecks > 0 && y < 240) {
        doc.setFontSize(14);
        doc.setTextColor(239, 68, 68);
        doc.text(`Bottleneck Alert (${bottlenecks} tasks)`, 15, y);
        y += 8;

        const delayed = projectWorks.filter(w => {
          if (w.status === 'completed') return false;
          const created = new Date(w.created_at).getTime();
          return (now - created) > 7 * 24 * 3600000;
        }).slice(0, 10);

        delayed.forEach(w => {
          const days = Math.floor((now - new Date(w.created_at).getTime()) / (24 * 3600000));
          doc.setFontSize(7);
          doc.setTextColor(100, 100, 100);
          doc.text(`- ${(w.task_name || '').substring(0, 40)} | ${w.project_name || ''} | ${days} days`, 18, y);
          y += 5;
        });
      }

      // ── Footer ──
      const pages = doc.getNumberOfPages();
      for (let i = 1; i <= pages; i++) {
        doc.setPage(i);
        doc.setFillColor(27, 43, 72);
        doc.rect(0, 290, pageW, 7, 'F');
        doc.setFontSize(7);
        doc.setTextColor(255, 255, 255);
        doc.text('Dar Wa Emaar - Project Tracker | Confidential', pageW / 2, 294, { align: 'center' });
        doc.text(`Page ${i}/${pages}`, pageW - 15, 294, { align: 'right' });
      }

      // Save
      doc.save(`DarWaEmaar_Executive_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('فشل إنشاء التقرير');
    } finally {
      setIsGenerating(false);
    }
  };

  // Quick stats for preview
  const totalProjects = projects.length;
  const completedProjects = projects.filter(p => p.status === 'completed' || p.progress >= 100).length;
  const avgProgress = totalProjects > 0 ? Math.round(projects.reduce((s, p) => s + (p.progress || 0), 0) / totalProjects) : 0;
  const bottlenecks = projectWorks.filter(w => {
    if (w.status === 'completed') return false;
    const created = new Date(w.created_at).getTime();
    return (Date.now() - created) > 7 * 24 * 3600000;
  }).length;

  return (
    <div className="w-full">
      <div className="flex items-center gap-3 mb-2">
        <FileText size={20} className="text-[#E95D22]" />
        <span className="cin-subtitle">التقرير التنفيذي</span>
      </div>
      <h2 className="text-3xl font-black text-[#1B2B48] mb-6">تقرير PDF جاهز</h2>

      <div className="glass-card p-6 glow-border" style={{ borderRadius: 20 }}>
        {/* Preview */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
          {[
            { label: 'المشاريع', value: totalProjects, icon: <BarChart3 size={14} />, color: '#1B2B48' },
            { label: 'مكتملة', value: completedProjects, icon: <CheckCircle2 size={14} />, color: '#22C55E' },
            { label: 'متوسط التقدم', value: `${avgProgress}%`, icon: <FileText size={14} />, color: '#E95D22' },
            { label: 'مختنقات', value: bottlenecks, icon: <AlertTriangle size={14} />, color: bottlenecks > 0 ? '#EF4444' : '#22C55E' },
          ].map(item => (
            <div key={item.label} className="rounded-xl bg-[#1B2B48]/[0.03] border border-[#1B2B48]/5 p-3 text-center">
              <div className="mx-auto mb-1" style={{ color: item.color }}>{item.icon}</div>
              <p className="text-lg font-black text-[#1B2B48]">{item.value}</p>
              <p className="text-[8px] text-gray-500 font-bold">{item.label}</p>
            </div>
          ))}
        </div>

        <p className="text-[10px] text-gray-500 mb-4 text-center">
          سيتم إنشاء ملف PDF يحتوي على: المؤشرات الرئيسية • جدول حالة المشاريع • تنبيهات المختنقات
        </p>

        {/* Generate Button */}
        <motion.button
          onClick={generatePDF}
          disabled={isGenerating}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className="w-full flex items-center justify-center gap-3 px-6 py-4 rounded-2xl font-black text-white text-sm transition-all disabled:opacity-50"
          style={{ background: 'linear-gradient(135deg, #E95D22, #1B2B48)' }}
        >
          {isGenerating ? (
            <>
              <Loader2 size={18} className="animate-spin" />
              جاري إنشاء التقرير...
            </>
          ) : (
            <>
              <FileDown size={18} />
              تحميل التقرير التنفيذي PDF
            </>
          )}
        </motion.button>
      </div>
    </div>
  );
};

export default ExecutivePDFReport;
